// <auto-generated />
namespace EasyWeixin.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class FirstInit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FirstInit));
        
        string IMigrationMetadata.Id
        {
            get { return "201506020930469_FirstInit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
